version: '3'

services:
  # Runs the Python server process:
  # Runs the JS client build and serve process:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    links:
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - '8080:8080'
      # Open this port to attach to remote debuggers in the Python process,
      # if need-be:
      - '33284:33284' # Spells "DEBUG" in phone-number
    stdin_open: true
    tty: true

  # Runs the database process:
  postgres:
    image: postgres:10.6
    environment:
      - POSTGRES_USER=metecho
    volumes:
      - ./postgres:/var/lib/postgresql/data:delegated

  # Runs the queue process:
  redis:
    image: redis:5.0

  # Sets up git hooks for local development:
  githooks:
    build:
      context: .
      dockerfile: ./compose/githooks/Dockerfile
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
